version: '3.1'

services:
  db-account:
    build:
      context: .
    container_name: account_db
    image: account_db
    ports:
      - "5432:5432"
    networks:
      - local

# Rede local para comunicacao dos containers
networks:
  local:
    driver: bridge